export const BLOOD_BOWL_RACES = [
  'Amazon', 'Black Orc', 'Chaos Chosen', 'Chaos Dwarf', 'Chaos Renegade',
  'Dark Elf', 'Dwarf', 'Elven Union', 'Goblin', 'Halfling', 'High Elf',
  'Human', 'Imperial Nobility', 'Khorne', 'Lizardmen', 'Necromantic Horror',
  'Norse', 'Nurgle', 'Ogre', 'Old World Alliance', 'Orc', 'Shambling Undead',
  'Skaven', 'Snotling', 'Tomb Kings', 'Underworld Denizens', 'Vampire',
  'Wood Elf',
  // Teams of Legend
  'Amazons (ToL)', 'Bretonnian (ToL)', 'Chaos Pact (ToL)', 'Corn (ToL)',
  'High Elf (ToL)', 'Kislev Circus (ToL)', 'Norse (ToL)', 'Slann (ToL)',
  'Undead (ToL)', 'Vampire (ToL)', 'Khemri (ToL)', 'Lustrian (ToL)',
];

export const RACE_POSITIONS: Record<string, string[]> = {
  Amazon: ['Linewoman', 'Thrower', 'Catcher', 'Blitzer'],
  'Black Orc': ['Goblin Bruiser Lineman', 'Trained Troll', 'Black Orc', 'Thrower', 'Blitzer'],
  'Chaos Chosen': ['Beastman Runner', 'Chaos Blocker', 'Minotaur'],
  'Chaos Dwarf': ['Chaos Dwarf Blocker', 'Hobgoblin', 'Bull Centaur', 'Minotaur'],
  'Chaos Renegade': ['Renegade Human Lineman', 'Renegade Goblin', 'Renegade Skaven', 'Ogre', 'Troll', 'Minotaur', 'Dark Elf', 'Orc', 'Skaven'],
  'Dark Elf': ['Lineman', 'Runner', 'Blitzer', 'Witch Elf'],
  Dwarf: ['Blocker', 'Runner', 'Blitzer', 'Troll Slayer', 'Deathroller'],
  'Elven Union': ['Lineman', 'Thrower', 'Catcher', 'Blitzer'],
  Goblin: ['Goblin', 'Bomma', 'Looney', 'Fanatic', 'Pogoer', 'Troll'],
  Halfling: ['Halfling Hopeful', 'Halfling Hefty', 'Halfling Catcher', 'Treeman'],
  'High Elf': ['Lineman', 'Thrower', 'Catcher', 'Blitzer'],
  Human: ['Lineman', 'Thrower', 'Catcher', 'Blitzer', 'Ogre'],
  'Imperial Nobility': ['Retainer Lineman', 'Bodyguard', 'Thrower', 'Blitzer', 'Ogre'],
  Khorne: ['Bloodborn Marauder Lineman', 'Bloodseekers', 'Khorngor', 'Bloodspawn'],
  Lizardmen: ['Skink', 'Saurus', 'Kroxigor', 'Chameleon Skink'],
  'Necromantic Horror': ['Zombie', 'Ghoul Runner', 'Wraith', 'Werewolf', 'Flesh Golem'],
  Norse: ['Lineman', 'Runner', 'Berserker', 'Ulfwerener', 'Yhetee'],
  Nurgle: ['Rotter Lineman', 'Pestigor', 'Bloater', 'Rotspawn'],
  Ogre: ['Ogre', 'Gnoblar'],
  'Old World Alliance': ['Lineman', 'Thrower', 'Catcher', 'Blitzer', 'Ogre', 'Dwarf Blocker', 'Halfling Hopeful', 'Troll Slayer'],
  Orc: ['Lineman', 'Thrower', 'Blitzer', 'Big Un Blocker', 'Goblin', 'Troll'],
  'Shambling Undead': ['Zombie', 'Skeleton', 'Ghoul Runner', 'Wight Blitzer', 'Mummy'],
  Skaven: ['Lineman', 'Thrower', 'Gutter Runner', 'Blitzer', 'Rat Ogre'],
  Snotling: ['Snotling', 'Fungus Flinga', 'Stilty Runner', 'Pump Wagon', 'Troll', 'Ogre'],
  'Tomb Kings': ['Skeleton', 'Thro-Ra', 'Blitz-Ra', 'Tomb Guardian'],
  'Underworld Denizens': ['Underworld Goblin', 'Skaven Lineman', 'Skaven Thrower', 'Skaven Blitzer', 'Troll', 'Snotling'],
  Vampire: ['Thrall', 'Vampire'],
  'Wood Elf': ['Lineman', 'Thrower', 'Catcher', 'Wardancer', 'Treeman'],
  // Teams of Legend (examples, not exhaustive)
  'Amazons (ToL)': ['Linewoman', 'Thrower', 'Catcher', 'Blitzer'],
  'Bretonnian (ToL)': ['Lineman', 'Blocker', 'Blitzer', 'Knight'],
  'Chaos Pact (ToL)': ['Marauder', 'Goblin', 'Skaven', 'Dark Elf', 'Ogre', 'Troll', 'Minotaur'],
  'Corn (ToL)': ['Bloodletter', 'Herald', 'Bloodthirster', 'Pit Fighter'],
  'High Elf (ToL)': ['Lineman', 'Thrower', 'Catcher', 'Blitzer'],
  'Kislev Circus (ToL)': ['Lineman', 'Catcher', 'Blitzer', 'Bear'],
  'Norse (ToL)': ['Lineman', 'Runner', 'Berserker', 'Ulfwerener', 'Yhetee'],
  'Slann (ToL)': ['Lineman', 'Catcher', 'Blitzer', 'Kroxigor'],
  'Undead (ToL)': ['Zombie', 'Skeleton', 'Ghoul Runner', 'Wight Blitzer', 'Mummy'],
  'Vampire (ToL)': ['Thrall', 'Vampire'],
  'Khemri (ToL)': ['Skeleton', 'Thro-Ra', 'Blitz-Ra', 'Tomb Guardian'],
  'Lustrian (ToL)': ['Skink', 'Saurus', 'Kroxigor', 'Chameleon Skink'],
}; 